[package]
name = "horizon"
description = "The software that powers VilaHack"
keywords = [ "ctf" ]

version = "0.1.0"
edition = "2024"
rust-version = "1.91"

license-file = "LICENSE"
readme = "README.md"

homepage = "https://vilahack.com/"
authors = [ "pol-epsevg <pol@vilahack.com>" ]
repository = "https://github.com/VilaHack/Horizon"

[dependencies]
# Asyncronous runtime
tokio = "1"

# HTTP server
axum = { version = "0.8", features = ["multipart", "macros"] }
axum-extra = { version = "0.12", features = ["cookie"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["cors"] }

# Database
mongodb = { version = "3", features = ["snappy-compression"] }

# Authentication
argon2 = "0.5"
hex = "0.4"
hmac = "0.13"
rand = { version = "0.10", features = ["thread_rng"] }
sha2 = "0.11"

# Email
lettre = { version = "0.11", features = ["tokio1-native-tls", "serde", "builder"] }
liquid = "0.26"

# Serialization / Deserialization
serde = { version = "1", features = ["serde_derive"] }
toml = "1"

# Observability
log = { version = "0.4", features = ["std"] }
logforth = { version = "0.30", features = ["append-opentelemetry", "layout-text", "filter-rustlog", "bridge-log"] }
metrics = "0.24"
metrics-opentelemetry = "0.24032"
opentelemetry = "0.32"
opentelemetry_sdk = { version = "0.32", features = ["metrics", "testing"] }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"] }

# Other
anyhow = "1"
utoipa = { version = "5", features = ["axum_extras", "uuid"] }

[profile.release]
lto = 'fat' # Perform link time optimizations for the whole dependency graph
codegen-units = 1 # Sacrifice compilation speed for a faster binary

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
