[package]
name = "horizon"
description = "The software that powers VilaHack"
keywords = [ "ctf" ]

version = "0.1.0"
edition = "2024"
rust-version = "1.88"

license-file = "LICENSE"
readme = "README.md"

homepage = "https://vilahack.com/"
authors = [ "pol-epsevg <pol@vilahack.com>" ]
repository = "https://github.com/VilaHack/Horizon"

[dependencies]
# Asyncronous runtime
tokio = { version = "1", features = ["macros"] }

# HTTP server
axum = { version = "0.8", features = ["multipart"] }

# Database
mongodb = { version = "3", features = ["snappy-compression"] }

# Authentication
hex = "0.4"
hmac = "0.13"
rand = { version = "0.10", features = ["thread_rng"] }
sha2 = "0.11"

# Serialization / Deserialization
serde = { version = "1", features = ["serde_derive"] }

# Observability
log = "0.4"

# Other
anyhow = "1"

[profile.release]
lto = 'fat' # Perform link time optimizations for the whole dependency graph
codegen-units = 1 # Sacrifice compilation speed for a faster binary

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
