# Example configuation file for Horizon
#
# Horizon will look for a configuration file at these default locations:
# - /etc/horizon/configuration.toml
# - /etc/horizon/config.toml
# - /etc/horizon/horizon.toml
#
# You can use an alterative configuration path by providing it as the first
# argument when running Horizon.

log_level = "info,horizon=trace" # Emmit all logs for Horizon and only logs of
                                 # `info` level or higher for Horizon's
                                 # dependencies

[authentication]
# Random set of 32 bytes, used as the HMAC key.
key = [
  84, 75, 240, 186, 31, 133, 254, 240, 131, 113, 48, 113, 143, 10, 161, 154,
  159, 198, 80, 114, 150, 145, 51, 250, 105, 105, 134, 89, 25, 176, 131, 184
]
session_timeout_ms = 28800000 # 8 hours

[http]
bind_address = "0.0.0.0:8000" # Listen on all network interfaces on port 8000
allowed_origins = [
  "https://my_ctf.com",       # Set of addresses that will be attached to HTTP
  "https://admin.my_ctf.com"  # responses as allowed origins (CORS)
]

[database] # MongoDB connection string
uri = "mongodb://horizon_db_user:super_secure_password@localhost:27017/my_ctf_db?appName=Horizon"

[smtp]
relay = "smtp.my_ctf.com" # SMTP Relay FQDN
credentials = {
    authentication_identity = "horizon_smtp_user",
    secret = "super_secure_password"
}

send_from = "My CTF <robot@my_ctf.com>"
reply_to = "Do not reply to this email <noreply@my_ctf.com>"

[smtp.templates]
verification = {
    subject = "[My CTF] Verify your email address",
    body = "verification_email.liquid.html" # File path to email liquid template
}                                           #  
                                            # The variable `url` is used for
forgot_password = {                         # the verification and password
    subject = "[My CTF] Password reset",    # reset templates.
    body = "forgotten_password_email.liquid.html"
}

application_acceptance = {
    subject = "[My CTF] You've been accepted! Please confirm your attendance",
    body = "application_accepted.liquid.html" # The variable `name` is
}                                             # available.
